### ISSUE TITLE
Some parenthsis missing, most packets missing

### ISSUE THREAD

**Issue by jeisch** [mjuenema/python-TSIP#1]
The code is incomplete and has a few typos.  It looks very promising though.  Can you push up a complete version?

**Comment by mjuenema** [comment]
Jonathan, I wish I had enough time to really work on it. But now, that I know that someone is actually interested in the project I should probably (re-)start work on it. So far I only ever needed a small subset of the TSIP features; to check the status of a Trimble Thunderbolt or to trigger a self-survey. I have to ask work whether I can borrow one of the Thunderbolts.

**Comment by jeisch** [comment]
I’ll need to implement some other things.  If you push up what ever you had working, I could add some other packets and help debug/maintain.  It would be more useful than both of us having a minimally working implementation.

-Jonathan

On Jun 18, 2015, at 2:31 AM, Markus Juenemann <notifications@github.com<mailto:notifications@github.com>> wrote:


Jonathan, I wish I had enough time to really work on it. But now, that I know that someone is actually interested in the project I should probably (re-)start work on it. So far I only ever needed a small subset of the TSIP features; to check the status of a Trimble Thunderbolt or to trigger a self-survey. I have to ask work whether I can borrow one of the Thunderbolts.

**Comment by mjuenema** [comment]
I actually thought of implementing a little lower level interface that parses the TSIP packets and then provides access to its fields by index instead of named attribute. Something along the line of:

gps = TSIP(serial_conn)
packet = gps.read()
if packet.code = 0x8feb:
    latitude = packet[4]

I don't have the TSIP reference here so I probably got the details wrong but you probably get the idea. This should be easier to implement with a little help of the Python bitstring module. Give me a couple of days and I can get started on it. I am going to upload the code to Github and you are most welcome to contribute. 

Markus

**Comment by mjuenema** [comment]
The basic structure of the project is set and the automatic output packets of Trimble Copernicus II have been implemented in the develop branch.

**Comment by mjuenema** [comment]
This issue has become obsolete as I started from scratch.
